create or replace TABLE tdl.CS_DAILY_ACTIVES (
    ID BIGINT IDENTITY(1,1),
	CUSTOMERID NUMBER(38,0),
	SOURCESYSTEM VARCHAR(3),
	SUBSCRIPTIONDIMKEY NUMBER(38,0),
	DATE DATE,
	VOLUME NUMBER(38,0),
	REVENUE_GBP FLOAT,
	REVENUE_USD FLOAT,
	PENDING_PAYMENT VARCHAR(16777216),
	PENDING_CANCELLATION VARCHAR(16777216),
	LATE_RENEWAL VARCHAR(16777216),
    ROWCREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
	ROWUPDATEDDATE TIMESTAMP_NTZ
);
