create or replace TABLE tdl.CS_MOVEMENTS 
(	
	ID BIGINT IDENTITY(1,1),
	CUSTOMERID NUMBER(38,0),
	SUBSCRIPTIONDIMKEY NUMBER(38,0),
	MOVEMENTGROUP VARCHAR(100),
	MOVEMENTCATEGORY VARCHAR(100),
	MOVEMENTREASON VARCHAR(100),
	VOLUME NUMBER(38,0),
	MOVEMENTDATE DATE,
	SOURCESYSTEM VARCHAR(20),
	ORIGINALMOVEMENTID nvarchar,
	ROWCREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
	ROWUPDATEDDATE TIMESTAMP_NTZ
  );
