
create or replace TABLE tdl.CS_SUBSCRIPTION_DIM 
(	
	ID BIGINT IDENTITY(1,1),
	CUSTOMERID NUMBER(38,0),
	SUBSCRIPTIONDIMKEY NUMBER(38,0),
	SUBSCRIPTIONREFERENCENO NVARCHAR,
	SOURCESYSTEM VARCHAR(20),
	STARTDATE DATE,
	ENDDATE DATE,
	REGION VARCHAR(200),
	REPORTINGREGION VARCHAR(200),
	SUBREGION VARCHAR(200),
	COUNTRY VARCHAR(200),
	PRODUCTGROUP VARCHAR(58),
	PRODUCTSUBGROUP VARCHAR(58),
	PRODUCT VARCHAR(100),
	VOLUMEOFTERMS VARCHAR(53),
	EDW_SUBTERM VARCHAR(60),
	SUBTERMBAND VARCHAR(16777216),
	PURCHASETYPE VARCHAR(100),
	PAYTYPE VARCHAR(100),
	OFFERTYPE VARCHAR(200),
	STATUS VARCHAR(100),
	TRIALIST VARCHAR(1),
	MIGRATIONFLAG VARCHAR(100),
	ROWCREATEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
	ROWUPDATEDDATE TIMESTAMP_NTZ
);
