create or replace TABLE TDL.FCX_USERS_MONTHLY_ACTIVITY_FACT (
    ID BIGINT IDENTITY(1,1),
	CONTACTID NVARCHAR,
	REFERENCE_MONTH BIGINT,
	STATUS NVARCHAR,
	ISNEWREGISTRANT NVARCHAR,
	REGISTRATION_DATE TIMESTAMP_NTZ,
	NUMBEROFVISITS BIGINT,
	NUMBEROFARTICLEVIEWS BIGINT,
	ACTIVEUSER NVARCHAR,
	ROWINSERTEDDATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROWUPDATEDDATE TIMESTAMP_NTZ
);
