Create or Replace Table GA_CLASSIC_NORMALIZED
 as
select hits_pr_cd.*,
hits_pr_cd.fullvisitorid || '_' ||  hits_pr_cd.visitid visitid_Combined,
DATEADD(S,hits_pr_cd.visitstarttime,'1970-01-01') visitstarttime_TS,
TIMESTAMPADD( ms , hits_pr_cd.time , DATEADD(S,hits_pr_cd.visitstarttime,'1970-01-01')) hittime,
session_cd.VISITDATE,
session_cd.CHANNELGROUPING,
session_cd.TOTAL_VISITS,
session_cd.TOTAL_HITS,
session_cd.TOTAL_PAGEVIEWS,
session_cd.TOTAL_BOUNCES,
session_cd.TOTAL_NEWVISITS,
session_cd.TOTAL_SESSIONQUALITYDIM,
session_cd.TOTAL_SCREENVIEWS,
session_cd.TOTAL_TIMEONSCREEN,
session_cd.TOTAL_TIMEONSITE,
session_cd.TOTAL_TOTALTRANSACTIONREVENUE,
session_cd.TOTAL_TRANSACTIONREVENUE,
session_cd.TOTAL_TRANSACTIONS,
session_cd.TOTAL_UNIQUESCREENVIEWS,
session_cd.TRAFFICSOURCE_REFERRALPATH,
session_cd.TRAFFICSOURCE_CAMPAIGN,
session_cd.TRAFFICSOURCE_SOURCE,
session_cd.TRAFFICSOURCE_MEDIUM,
session_cd.TRAFFICSOURCE_KEYWORD,
session_cd.TRAFFICSOURCE_ADCONTENT,
session_cd.TRAFFICSOURCE_ISTRUEDIRECT,
session_cd.TRAFFICSOURCE_CAMPAIGNCODE,
session_cd.DEVICE_BROWSER,
session_cd.DEVICE_BROWSERVERSION,
session_cd.DEVICE_BROWSERSIZE,
session_cd.DEVICE_OPERATINGSYSTEM,
session_cd.DEVICE_OPERATINGSYSTEMVERSION,
session_cd.DEVICE_ISMOBILE,
session_cd.DEVICE_MOBILEDEVICEBRANDING,
session_cd.DEVICE_MOBILEINPUTSELECTOR,
session_cd.DEVICE_MOBILEDEVICEINFO,
session_cd.DEVICE_MOBILEDEVICEMARKETINGNAME,
session_cd.DEVICE_FLASHVERSION,
session_cd.DEVICE_JAVAENABLED,
session_cd.DEVICE_LANGUAGE,
session_cd.DEVICE_SCREENCOLORS,
session_cd.DEVICE_SCREENRESOLUTION,
session_cd.DEVICE_DEVICECATEGORY,
session_cd.DEVICE_MOBILEDEVICEMODEL,
session_cd.GEONETWORK_CONTINENT,
session_cd.GEONETWORK_COUNTRY,
session_cd.GEONETWORK_REGION,
session_cd.GEONETWORK_METRO,
session_cd.GEONETWORK_CITY,
session_cd.GEONETWORK_NETWORKDOMAIN,
session_cd.GEONETWORK_LATITUDE,
session_cd.GEONETWORK_LONGITUDE,
session_cd.GEONETWORK_NETWORKLOCATION,
session_cd.GEONETWORK_SUBCONTINENT,
session_cd.GEONETWORK_CITYID,
session_cd.PUGPIG_FEED,
session_cd.FILLER01,
session_cd.FILLER02,
session_cd.FILLER03,
session_cd.FILLER04,
session_cd.FILLER05,
session_cd.FILLER06,
session_cd.FILLER07,
session_cd.FILLER08,
session_cd.FILLER09,
session_cd.FILLER10,
case
        when length(hits_pr_cd.DRUPAL_ID) > 10 then "SDL_FCX".convert_ascii_to_string(hits_pr_cd.DRUPAL_ID)
        else hits_pr_cd.DRUPAL_ID
    end as UNHASHED_SFDC_CONTACTID
from "TDL"."GA_CLASSIC_HITS_PIVOT" hits_pr_cd,
"TDL"."GA_CLASSIC_SESSION_PIVOT" session_cd
where hits_pr_cd.visitNumber=session_cd.visitNumber(+) and 
hits_pr_cd.visitId=session_cd.visitId(+) and 
hits_pr_cd.fullVisitorId=session_cd.fullVisitorId(+) and
hits_pr_cd.visitStartTime=session_cd.visitStartTime(+);