create or replace TABLE TDL.LIM_PURCHASE_ABANDONED (
	BASKET_ID VARCHAR(200),
	PRODUCT_NAME VARCHAR(100),
	SUBS_TYPE VARCHAR(100),
	CONTACTID VARCHAR(500),
	ACCOUNTID VARCHAR(200),
	CUSTOMERSTATUS VARCHAR(200),
	COMPLETED BOOLEAN,
	ROW_CREATED_DT TIMESTAMP_NTZ(9),
	ROW_CREATED_BY VARCHAR(50),
	ROW_UPDATED_DT TIMESTAMP_NTZ(9),
	ROW_UPDATED_BY VARCHAR(50),
	SOURCE_CREATED_DT TIMESTAMP_NTZ(9),
	SOURCE_UPDATED_DT TIMESTAMP_NTZ(9)
);