create or replace TABLE SFDC_TENURE_OUTBOUND (
	SFDC_CONTACTID VARCHAR(18) NOT NULL,
	FIRST_SUBS_START_DATE DATE,
	MOST_RECENT_SUB_START_DATE DATE,
	MOST_RECENT_LAPSED_DATE DATE,
	ROWUPDATEDDATE TIMESTAMP_NTZ(9) NOT NULL,
	SFDC_PERSONACCOUNTID VARCHAR(18),
	LOADID VARCHAR(60),
	SUCCESS_FLAG BOOLEAN,
	ERROR VARCHAR(500),
	VOLUME_OF_TERMS NUMBER(38,0),
	STATUS VARCHAR(255),
	SEGMENT__C VARCHAR(255),
	primary key (SFDC_CONTACTID)
);
