create or replace TABLE SFDC_TENURE_OUTBOUND_TEMP (
	SFDC_CONTACTID VARCHAR(18),
	FIRST_SUBS_START_DATE TIMESTAMP_NTZ(9),
	MOST_RECENT_SUB_START_DATE TIMESTAMP_NTZ(9),
	MOST_RECENT_LAPSED_DATE DATE,
	ROWUPDATEDDATE timestamp,
	SFDC_PERSONACCOUNTID VARCHAR(18),
	VOLUME_OF_TERMS NUMBER(38,0)
);